version: '3.8'

services:
  # MCP Gateway Principal
  mcp-gateway:
    image: nginx:alpine
    container_name: borboleta-mcp-gateway
    ports:
      - "3000:80"
    networks:
      - mcp-network
    volumes:
      - ./config/mcp-gateway/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    labels:
      - "com.docker.mcp.type=gateway"
      - "com.docker.mcp.role=orchestrator"

  # N8N Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: borboleta-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=borboleta123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - MCP_GATEWAY_URL=http://mcp-gateway:3000
      - SUPABASE_URL=${VITE_SUPABASE_URL:-https://pxcvoiffnandpdyotped.supabase.co}
      - SUPABASE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - N8N_ENCRYPTION_KEY=borboleta-n8n-encryption-key-2025
    volumes:
      - n8n_data:/home/node/.n8n
      - ./config/n8n:/etc/n8n
      - ./workflows/n8n:/workflows
    networks:
      - mcp-network
    depends_on:
      - mcp-gateway
    restart: unless-stopped
    labels:
      - "com.docker.mcp.type=automation"
      - "com.docker.mcp.service=n8n"
      - "com.docker.mcp.project=borboleta-eventos"

  # Application Server (nosso projeto)
  app:
    build: .
    container_name: borboleta-eventos-loja-app-1
    ports:
      - "5173:5173"
      - "8812:8812"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-https://pxcvoiffnandpdyotped.supabase.co}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
      - MCP_GATEWAY_URL=http://mcp-gateway:3000
      - MCP_ENABLED=true
      - N8N_WEBHOOK_URL=http://n8n:5678
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mcp-network
    depends_on:
      - mcp-gateway
      - n8n
    restart: unless-stopped
    labels:
      - "com.docker.mcp.type=client"
      - "com.docker.mcp.project=borboleta-eventos"

networks:
  mcp-network:
    driver: bridge
    name: borboleta-mcp-network
    labels:
      - "com.docker.mcp.network=true"

volumes:
  n8n_data:
    name: borboleta-n8n-data
