// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdswhhckvweghcavgdvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkc3doaGNrdndlZ2hjYXZnZHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTU0NjIsImV4cCI6MjA3MTEzMTQ2Mn0.8ei1-GdvgWdr_X6BC0Wh2Rr8USJfIDStM0vNY9MGk1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});